version: "3.8"
services:
  backend:
    container_name: nest-backend
    build: ./backend/docker
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    command: bash -c "yarn start:dev"
  frontend:
    container_name: next-frontend
    build: ./frontend/docker
    tty: true
    ports:
      - "8000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    command: bash -c "cd app && yarn dev"
